# Generated by Django 3.1.3 on 2022-11-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0007_auto_20201129_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='category',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='Masculino', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('COLOCADO', 'Seu pedido foi feito'), ('CANCELADO', 'Seu pedido foi cancelado'), ('EMBALADO', 'Seu pedido está embalado'), ('ENVIADO', 'Seu pedido está pronto para envio')], max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Na Entrega'), ('ONLINE', 'Online')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size',
            field=models.CharField(choices=[('S', 'Pequeno'), ('M', 'Médio'), ('L', 'Grande'), ('XL', 'Extra Grande'), ('XXL', 'Extra Extra Grande')], max_length=5),
        ),
    ]
