# Generated by Django 3.1.3 on 2022-11-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0008_auto_20221111_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='category',
            field=models.CharField(choices=[('m', 'masculino'), ('f', 'feminino')], default='masculino', max_length=10),
        ),
    ]
